# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  name: Agent-Windows

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '11.0.19'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    options: '-DskipTests=true -e -X'
    goals: 'clean install'

# Etapa para executar os testes
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '11.0.19'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    options: '-e -X'
    goals: 'test'

# Etapa para publicar os resultados dos testes
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/surefire-reports/*.xml'
    failTaskOnFailedTests: true
